export const copy = {
    en: {
        title: 'Categories',
        intro: 'Organize the kinds of work available on Elancer.',
        active: 'Active',
        deleted: 'Deleted',
        create: 'Create category',
        edit: 'Edit',
        categoryname: 'Category name',
        actions: 'Actions',
        remove: 'Delete',
        restore: 'Restore',
        cancel: 'Cancel',
        save: 'Save changes',
        saving: 'Saving…',
        empty: 'No active categories. Create your first category.',
        emptyDeleted: 'No deleted categories.',
        previous: 'Previous',
        next: 'Next',
        page: 'Page',
        of: 'of',
        total: 'categories',
        back: 'Back to categories',
        hint: 'Enter the category name in English or Arabic.',
        confirm:
            'Delete this category? You can restore it from the Deleted list.',
        error: 'The request failed. Please try again.',
        invalid: 'Check the highlighted fields.',
        created: 'Category created.',
        updated: 'Category updated.',
        deletedNotice: 'Category deleted.',
        restored: 'Category restored.',
        security: 'Two-factor authentication required',
        setup: 'Enable and confirm two-factor authentication in security settings. Then log out and log in with your password and authentication code.',
        login: 'Log out, then log in with your password and authentication code to access category management.',
        settings: 'Security settings',
        logout: 'Log out',
    },
    ar: {
        title: 'التصنيفات',
        intro: 'نظّم أنواع العمل المتاحة على إيلانسر.',
        active: 'النشطة',
        deleted: 'المحذوفة',
        create: 'إنشاء تصنيف',
        edit: 'تعديل',
        categoryname: 'اسم التصنيف',
        actions: 'الإجراءات',
        remove: 'حذف',
        restore: 'استعادة',
        cancel: 'إلغاء',
        save: 'حفظ التغييرات',
        saving: 'جارٍ الحفظ…',
        empty: 'لا توجد تصنيفات نشطة. أنشئ أول تصنيف.',
        emptyDeleted: 'لا توجد تصنيفات محذوفة.',
        previous: 'السابق',
        next: 'التالي',
        page: 'صفحة',
        of: 'من',
        total: 'تصنيف',
        back: 'العودة إلى التصنيفات',
        hint: 'أدخل اسم التصنيف بالعربية أو الإنجليزية.',
        confirm: 'حذف هذا التصنيف؟ يمكنك استعادته من قائمة المحذوفات.',
        error: 'تعذر تنفيذ الطلب. حاول مجدداً.',
        invalid: 'راجع الحقول المحددة.',
        created: 'تم إنشاء التصنيف.',
        updated: 'تم تحديث التصنيف.',
        deletedNotice: 'تم حذف التصنيف.',
        restored: 'تمت استعادة التصنيف.',
        security: 'المصادقة الثنائية مطلوبة',
        setup: 'فعّل المصادقة الثنائية وأكّدها في إعدادات الأمان. ثم سجّل الخروج وادخل بكلمة المرور ورمز المصادقة.',
        login: 'سجّل الخروج، ثم ادخل بكلمة المرور ورمز المصادقة لإدارة التصنيفات.',
        settings: 'إعدادات الأمان',
        logout: 'تسجيل الخروج',
    },
};
export type Category = {
    id: number;
    categoryname: string;
    slug: string;
};
